### ISSUE TITLE
[Discussion] Contract language ideas

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#195]
# Contract language

*Everything in this issue description is a subject to discussion and will be dynamically changed*

First step of deciding how a contract language should look like is to list the requirements.

## High Level requirements

1. possible to implement formulas for voting (and optionally voting)
2. possible to implement multi-sign wallets
3. possible to implement sub currencies (although we may want some native help for that)
4. possibility to reuse code deployed by others
5. possible to upgrade contracts
6. functional language
7. strongly and statically typed - every input, output has to have explicit defined type and conversions have to be explicit
8. minimal overhead

## Proposal

Lets split contracts with states and balance from code without state.

### Functions Low Level requirements 

- Every function is public on blockchain and can be referenced by it's crypto hash. (Do we allow functions inside functions? If so those will be private probably.)
- Functions have no side-effects.
- Every function gets a tuple and returns a tuple.
- Function may call itself.
- Access to data the function wasn't passed can be implemented by creating "special" functions. We have to be careful with this. This makes it so the effect of a transaction that "interacts" with function might not be possible to determine before it's executed. For miner: This also will make it (way) harder to reuse once calculated functions return values when a block (by someone else) is mined. 
Some suggested special functions:
    - get account data - gives tuple with all account data
    - get tx by hash
    - get contract data 
    - get current height
- There are following types:
    - char
    - (safe?) integer - we can create many types of integers of different sizes, but I think we should provide natively "safe integers" - that is integers that "never" overflow (raise exception when overflowing)
    - lists
    - predefined length table - allow const time reference to elements of the same time (e.g. addresses)
    - tuples - allow const time reference to elements of different types, probably slower then tables (e.g. arguments to functions, can represent structures)
- There also have to be some of the following:
    - maps
    - variants/unions - a value that contains one of any number of possible data types and information what data type it contains
    - recurrent types - a possibility to have a value of the same type inside value of given type. (this obviously depends on unions)

### Functional language internals

*TODO*

#### Idea A

- Whenever a transaction "affecting" contract is (tried) to be made a function is called.
- Account making a transaction affecting a contract pays the fee for that transaction. 
- Contracts have state. State is a tuple. It consists of:
    - data - a tuple of anything, used for storing any state information
    - table of function hashes - a table with separate functions (hashes) for different transaction types affecting the contract. Every function takes a tuple of state and transaction and returns new state:
        - tokens received - function used to handle a situation when someone sends a tx with tokens to this contract. That tx can contain data for contract. The person sending the tx has to pay for it's execution.
        - internal - function used to handle transaction without tokens. Such tx contains only data and address of account that created it.
        - transaction create - function used to create a transaction as contract. This tx contains data, address of account that created it and tx to be made on chain as the contract.

#### Idea B

- There is only one transaction type affecting contract. Transaction to contract with data and tokens. The amount of tokens might by 0. Account making this transaction pays for its execution.
- Contract has state. State is a tuple of:
    - data - a tuple of anything, used for storing any state information
    - handling function hash - function with this hash is used to handle any transaction to contract. It get's state and transaction. It returns new state and (possibly empty) list of transactions to make on blockchain as the contract.

## Issues

- Fees when a contract is involved have to be well thought about. Sometimes (e.g. see OffChainFormula solution for voting) we might want to make it so the person executing a function doesn't pay for it, but contract pays instead. (e.g. someone executing some previous function paid for this execution). 
- Having access to transactions in function (if a transaction is passed or created by function) can make is so we have to have unions and recurrent types. (example of a case when such types might be required: we might want a contract to call a contract that will call a contract that will call a contract)

## Other ideas

- Maybe even Erlang or Elixir can be our function language? My research suggests it's possible to securely (without possibility of making malicious calls) evaluate functions on runtime.
- Before creating our own language we should definitely research existing languages.

**Comment by cytadela8** [comment]
@thepiwo

**Comment by untra** [comment]
> Maybe even Erlang or Elixir can be our function language? My research suggests it's possible to securely (without possibility of making malicious calls) evaluate functions on runtime.

Elixir does provide wonderful support for macros, and making a DSL out of elixir macros has been done before, and is a well-documented endeavor. Same goes for Erlang, but Elixir is famous for it's metaprogramming.

Overall, I think prospective developers would greatly appreciate not having to learn another language to write blockchain smartcontracts in. The easier it is to onboard developers to a new smart contract platform, the better.

**Comment by cytadela8** [comment]
@untra: Are you aware of any existing utilities/libraries that can sandbox elixir? I found only this repo: https://github.com/christhekeele/exbox, but it has in readme: "Status: proof-of-concept".

**Comment by vans163** [comment]
@untra Ugh, elixir macros are dirty and nasty. When they work they work, but they are not flexible enough and I find myself having to do manual AST manipulation to get the behaviour I want out of macros.

@cytadela8 A sandbox should be elementary to make by parsing the AST. Just parse the entire AST, then run the functions called vs a list of allowed or not allowed modules/functions.

I vote for AST as the target language, then people can write smart contracts in Erlang, Elixir, LispFlavor, etc, anything that has AST target.  A javascript->AST compiler and more can be developed in future.

**Comment by untra** [comment]
> I vote for AST as the target language, then people can write contracts in Erlang, Elixir, LispFlavor, etc,

I really like this idea; considering that the goal is to implement a new smart contract language, having it compile to an AST that can be run on the BEAM would be incredibly powerful.

There are still questions though around type safety, and how gas/transaction fees are paid out. There may need to be modifications to the BEAM to handle these details.

**Comment by untra** [comment]
#### Idea C : Smart Contracts as Finite State Machines
Almost everyone understands [finite state machines](http://learnyousomeerlang.com/finite-state-machines), what they can be used for, and how to reason about complex systems with them. They are conducive to functional programming and formal verification.

In contrast to solidity smart contracts, rather than paying a transaction fee (gas) and specifying a gas limit with every transaction made against a contract, these contracts maintain their own retainer of gas tokens. This allows a contract to pay for it's own autonomous state transitions. When a contract completes, leftover gas in the contract can be returned. Additional gas can be added to a contract as part of calling any function, but providing gas is not always mandatory when interacting with a smart contract. It should be possible to recover a well-designed contract from "OutOfGas" and other operational errors.

* Uploading a contract to the blockchain is it's own transaction.
  * _input:_ `contract_code :: ast`, `initial_gas :: non_negative_integer`
  * Whoever executes this transaction must provide the initial gas for the contract. This will be used to pay the fee for adding the contract to the chain, and for enabling further operations by the contract.
  * If successfully uploaded, it's `handling function hash` and current state is returned.
* Contract code defines operational states the contract may arrive into, as well as :
  * *Entry:* automatic operations performed whenever transitioning into this state (from another state)
  * *Exit:* automatic operations performed whenever transitioning away from this state (into a new state)
  * *Transitions:* these are functions that can be called when at a particular state in a contract. All functions will cause a state transition, but a transition can go back to the same state. These can be explicit, like a user making a transaction to invoke a function on a defined contract, or automatic, like an oracle providing an answer to an event.
  * *Required:* only two special states must be explicitly defined: `init` and `terminated`.
* Contracts can have a finite number of defined states.
  * ✔️ entry ✔️  exit ✔️ transitions ❌ required
  * defined states must define at least one transition into the state, and at least one transition away from the state for a contract to be correct.
* Contracts admit admit four special states:
  * They have an `init` state.
    * ❌ entry ✔️  exit ✔️ transitions ✔️ required
    * All contracts will start in this state after being uploaded.
    * At least one transition from `init` into another state is required
    * Contracts should provide transitions from the initial state to other states.
  * They have an `error` state.
    * ❌  entry ❌  exit ✔️ transitions ❌ required
    * A contract can transition to this state at any time, from any other state (except for `terminated`)
    * A "OutOfGas" error is the typical reason a contract will transition to this state, but other operational exceptions may send it here (eg. division by zero).
    * A contract in error can only transition to the `recovery` state.
    * A contract in error cannot return to any other state without first entering the `recovery` state.
    * Because the error state is not required to be defined by contract code, it is possible for contracts to get "stuck" in the error state.
  * They have a `recovery` state.
    * ❌ entry ✔️  exit ✔️ transitions ❌ required
    * A contract can only transition from the error state through recovery, and can only enter recovery from error.
    * Entry to the recovery state from error requires additional gas be provided
    * A contract cannot automatically enter recovery ; a user must explicitly make a call to transition a contract into recovery from error.
    * It should be possible to return a contract to the state it was previously in, before it entered the error state, from the recovery state.
  * They have a `terminated` state.
    * ✔️ entry ❌ exit ❌ transitions ✔️ required
    * This is the final state the smart contract can enter into.
    * At least one transition into `terminated` is required.
    * No other state transitions from terminated are allowed.
    * It is at this state remaining gas in the contract should be handled.
    * If an error occurs when at terminated, all remaining gas is lost as a penalty fee.
    * Any remaining gas is forfeited.
    * Contracts should finish in terminated with no remaining gas.
* Calling a function defined in a contract is it's own transaction.
  * _input:_ `contract_hash :: hash`, `function_name :: atom`, `additional_gas :: non_negative_integer`, `function_data :: map`
  * If the contract corresponding with the `contract_hash` exists, and is in a state where `function_name` is available to be called, then the `additional_gas` will be added to the `gas_reamining`, and `function_name` will be called.
  * all defined transition functions have a similar signature: `function_name(callee, gas, history, context_data, function_data)`
    * `callee`: address of who called the function.
    * `gas`: remaining gas held by the contract.
    * `history`: a record of previous state transitions.
    * `context_data`: a single map/json-esque structure that gets stored on the blockchain and is available for other transactions
    * `function_data`: a single map/json-esque structure that was provided by the callee when calling this function
  * all transition functions must return `{new_state, gas, context_data}`, which gets stored on the chain
* Contracts are stored in two different parts of the chain:
  * The contract code/ast and its `function_hash` are stored on one part of the chain. These values don't ever change.
  * The current state of the contract is stored separately. This includes:
    * `gas_remaining :: int` in the contract
    * a history of all previous state transitions
    * `context_data :: map` a single map/json-esque structure for storing contextual data carried between state changes.

❓ So what did I get wrong? What isn't going to work here? I didn't focus on the contract language fundamentals, just the high-level details about contract implementation. Did I goof on any critical fundamentals?

**Comment by cytadela8** [comment]
@untra Your idea is very interesting, but I don't (personally) see a real point to defining those states. In practice one could make a big "if ... else if ... else if ..." structure in contract handling code. Also I'm against any kind of "error" state. I think we should prevent any transaction that would result in error state from executing and just consume gas for it. I'm against, because the "recovery" could be a big place for horrible errors.

Could you elaborate more why do you think it would be a good idea of adding the "states" concept on protocol level?

**Comment by cytadela8** [comment]
@vans163 Thanks for your comment. Parsing the AST manually looks good then. I will definitively look more into that.

**Comment by untra** [comment]
> Could you elaborate more why do you think it would be a good idea of adding the "states" concept on protocol level?

So I just started typing that idea at around 10pm, and then I got a _little_ carried away and didn't stop until midnight, lol. I've been thinking about it, and there are some details there that would make the idea totally unworkable in practice. It needs more thought, definitely.

But I was thinking about the personal user experience around smart contract development. It is currently exceedingly difficult for reasons related to contract performance (gotta keep that code slim when every variable allocation counts), formal verification (especially difficult to prove a smart contract has no bugs), and reasoning about contract operations.

Finite state machines do a good job of splitting operations into distinct _stages_, that can be independently reasoned about. Thinking about traditional contracts, they are usually written in a manner defining specific dates, operations, and conditions triggering clauses. Consider a scenario like:
`Party A agrees to sell X quantity of apples to Party B on date Y, with payment due upon receipt of the apples`
So contract states may look like:
> init -> party A signs -> party B signs -> awaiting oracle response -> oracle says apples arrived -> automatic payment from B to A

Ideally, the contract should only be awaiting the signatures from A and B. Assuming oracles are a solved problem, everything else should be automatic. But programming a contract to wait for input at a given interval gets tricky.

You may also have something like `a committee voting on a new chairperson`:
> init -> chairman proposes a new chair election -> awaiting votes -> vote received and tallied -> awaiting votes -> vote received and tallied ... -> awaiting votes -> chairperson says voting is over -> results say person X won the election -> person X is now the chairman

In a situation like this, "vote received and tallied" is the asynchronous event that requires someone to interact with the contract. But then it should immediately arrive back at the "awaiting votes" stage. Its a finite number of stages, but the number of transitions between stages can be huge.

A lot of "traditional" contract use-cases lend themselves nicely to finite state machines. And finite state machines kick ass 😉

**Comment by cytadela8** [comment]
Ok, I understand, so I think we should keep in mind designing the language in such a way that this common usecase (deciding on what code should handle tx based on contract state) can be efficiently implemented.

**Comment by AndrewDryga** [comment]
I hope nobody is against my points here :). You should not use Elixir or Erlang for smart contracts. There is no good solution to sandbox the code execution and even traversing Elixir or Erlang AST is a no-way, mainly because then you would have something like whitelist or blacklist of rules. Humans are not really good with their creation and maintenance, which leads to vulnerabilities.

(There is a thread on Elixir Forum where people discuss that and Robert Virding pointed that Beam is not a good option, and this is because a design of the language solves completely another purpose and they never had a task to do something like that. This is also the reason why we don't have lightweight Elixir playground.)

An option which I'm considering in my research to don't build/implement anything like EVM, instead of that we might accept arbitrary Elixir code from third-party developers, which can be organized in apps in the umbrella, this code can be just invoked and executed. This limits the scope of whatever should be accepted (only very common pieces should be part of blockchain core), but gives a common ground for all blockchain users:
- it's easy to rollout bugfix for all the users;
- it's much easier to interact between such contracts;
- all code is community audited. I know this is not a silver bullet, but even for crypto-token ICO investors it should be preferred becase they know when an ICO follows community best practice;

This approach would also require us to implement a completely new way to deliver updates, like global hotcode reloading with consensus on source/binary version. And it would require us to think of a way to simply build sidechain which uses that common pieces in the core and works efficiently, something like Plasma.

**Comment by thepiwo** [comment]
Thank you for your awareness @AndrewDryga, we are aware of this fact and this prototype would simply be experimentation in different directions.
You can find the current specifications for the aeternity smart contract language and vm here: https://github.com/aeternity/protocol/blob/master/contracts/contracts.md

Maybe @cytadela8 wants to have a more detailed answer to your comment, as he lead this prototypes effort.

**Comment by vans163** [comment]
@AndrewDryga What you said is not a solid argument.

#1 " mainly because then you would have something like whitelist or blacklist (even worse) of calls. Humans are not really good with their creation and maintenance, which leads to vulnerabilities"

 << This is how just about almost every sandbox (chromium, freebsd jails, etc) works. You can lose faith in humanity to properly sandbox their app, but at least make it easy then like AppArmor does, and leave the hard stuff for the curious+persistent.

#2 "An option which I'm considering in my research to don't build/implement anything like EVM, instead of that we might accept arbitrary Elixir code from third-party developers, which can be organized in apps in the umbrella, this code can be just invoked and executed."

<< This is the same as dealing with AST, Elixir code is just AST at the end of the day. There is really no difference between executing Elixir and directly executing AST. You wont code in AST of course, you will code in Elixir.

#3. "This approach would also require us to implement a completely new way to deliver updates, like global hotcode reloading with consensus on source/binary version."

<< I like this. But Elixir compiler needs fixing, it currently does not have hot code reloading working in a stable way without using releases. This is due to the way the parallel compiler works and how modules get purged during the process to properly support macros and protocols.

**Comment by AndrewDryga** [comment]
@thepiwo I've read the whitepaper so you can threat the last paragraph as a suggestion, in case that's still open for discussion. I understand that changing concepts in the middle of the road usually is not an option.

@vans163 

1. This is not how it works in Chromium, incognito mode, for example, runs a completely separate process which is isolated from main process. Same for jails, each jail runs in a process namespace and those processes can not interact with each other. Which is not true for Elixir, whole VM runs in a single context, even when you have distributed setup.

2. That's true, but the change is more philosophical. When you can deploy *anything* to an EVM, you can't deploy anything by opening a PR to the core. The core can have only the very common building blocks (like multisig wallets, payment channels implementation, common ICO contract) which are audited by all the community. There is no need to isolate them, however, I'm not sure how to implement something like "gas cost" on top of that. Overall, this is just an idea.

3. I know that people are working on releases right now, I think we will see changes within next 3-4 months. Overall, Elixir release is an OTP release and everything should be doable.

**Comment by AndrewDryga** [comment]
Here is the discussion I'm referring to: https://elixirforum.com/t/how-to-create-a-sandbox-to-run-untrusted-code-modules/4142/7.

**Comment by thepiwo** [comment]
> An option which I'm considering in my research to don't build/implement anything like EVM, instead of that we might accept arbitrary Elixir code from third-party developers, which can be organized in apps in the umbrella, this code can be just invoked and executed. This limits the scope of whatever should be accepted (only very common pieces should be part of blockchain core), but gives a common ground for all blockchain users

@AndrewDryga this is a very good idea to experiment with, but for aeternity core specifications the focus on building a version of the EVM and a new wardened VM is fixed.

@vans163 as I understand this would not be the "same as dealing with AST", but more of a plugin system to be updated with soft/hard-forks

**Comment by AndrewDryga** [comment]
@thepiwo the core idea is that most of blockchains don't need turning-complete contracts (even though this idea sounds really nice), they need base building blocks which are proven to work, and which can be used to build something on top of that. The blockchain itself can act like one large self-governed system, even in terms of software versions. It would be pretty easy to implement feature-based governance when nodes vote on software update and everybody MUST apply the code change after a certain threshold. Fortunately, with BEAM it's pretty easy to apply code changes. Same would apply to scripting languages.

**Comment by vans163** [comment]
@AndrewDryga Right so for point 

#1, I have a javascript vuln and get remote code execution (linux target), how does chrome sandbox (this separate process/+namespace) prevent me from calling sendmsg(sock,&msg,0) ?

#2, is cool and can work. The way modules work though on BEAM is that itl need a prefix to avoid collisions, but the module prefix could be the address of the contract, problem solved, heck that could be the full module name.

**Comment by cytadela8** [comment]
@AndrewDryga I agree with your points. The problems with this proposals were understood while doing research for it. What I think you pointed out and what was the problem found in the research phase is the BEAM isn't meant to implement any sandboxing. So although implementation of this proposal (#237) might do proper whitelisting of function calls it may be possible to achieve arbitrary code execution by creating an AST that doesn't conform (in some way) to specification and exploiting an security problem in BEAM. Compared to proper sandbox applications BEAM isn't meant to do any sandboxing, so its not meant be secure, so there is a high chance some vulnerability in it. 

Example for better understanding of the underlying issue:
Javasctipt is an language that isn't suppose to implement any sandboxing or separation inside of it's VM. The effect of that is you can achieve arbitrary code execution (inside of the VM that runs all the Javascript code) with only 6 chars (http://www.jsfuck.com/)

**Comment by AndrewDryga** [comment]
Yes. And It's just very hard to have up to date AST filtering rules, everything changes rapidly, for eg. if there is any function that accepts mfa tuple we would get a remote code execution vuln.

**Comment by vans163** [comment]
This discussion is turning into nonsense. How can you make a "AST that doesn't conform...exploit security problem in BEAM" , you have the entire documentation /+ source code to parse the AST correctly, and catch the one way functions can be called, :erlang.apply.  Everything is an Erlang process can be perfectly sandboxed via this approach.  Up to date AST filtering rules, this sounds like nonsense, rapidly changing? The AST parsing hasnt had significant changes in like 20 years, while the rest of the language has.  "if there is any function that accepts mfa tuple we would get a remote code execution  vuln.", what lol?

**Comment by thepiwo** [comment]
thank you for all of your discussions, ideas and general input to the project. I will close this issue for now, as the elixir-node will aim to replicate the aevm and other vms as proposed for the epoch project. Progress can be tracked here: https://github.com/aeternity/elixir-node/issues/275.

Other language prototypes will not be considered in the near future.
