### ISSUE TITLE
represent account chain state as tree

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#254]
right now the account chain state is a map of public keys to their data, this should be represented by a tree structure, for now `:gb_merkle_trees` to save and fetch each data by their key from the tree.

**Comment by rdimitrovbg** [comment]
By default 'gb_merkle_trees' works with binaries both for key and values.
We will have no problem with the public key because it is in the correct format.
But the accounts' structure must be transformed (to binary) to meet the requirement.
Which mechanism shall we use ? The one that erlang provides aka term_to_binary or something else ?

**Comment by thepiwo** [comment]
can you discuss with @meivantodorov and @HristianHristov if this is the case with patricia merkle trees as well?

**Comment by thepiwo** [comment]
I just looked up the epoch code and asked the core team.

We will have to represent our data in binary, the core team uses `term_to_binary` (subject to change) and in other cases `ethereum rlp`.
I propose we go with `msgpack` for now and monitor the changes by the core team.

**Comment by thepiwo** [comment]
closed by #317
