### ISSUE TITLE
nil.refs error in add_validated_block function

### ISSUE THREAD

**Issue by 0legIv** [aeternity/elixir-node#393]
There is an error that appear when running two separate nodes. When you run two synchronized nodes (one is mining) for the first time, everything is ok. But when you try to restart them there is an error:

[error] GenServer Aecore.Chain.Worker terminating
** (UndefinedFunctionError) function nil.refs/0 is undefined (module nil is not available)
    nil.refs()
    (aecore) lib/aecore/chain/worker.ex:353: anonymous fn/3 in Aecore.Chain.Worker.handle_call/3

https://github.com/aeternity/elixir-node/blob/b8c5a1e2c9db022731edae0a0aaf506c1b4a4fe4/apps/aecore/lib/aecore/chain/worker.ex#L353   -   the line where error appears

**Comment by gspasov** [comment]
The error might be happening because for some reason the Genesis block dissapears when we exit and enter the iex again. Maybe it has something to do with the persistense? I'm not quite sure. While this check is fine, we need to fix the core of this problem which might be just the missing first block (aka Genesis block).

**Comment by cytadela8** [comment]
I added [comments in the commit](https://github.com/aeternity/elixir-node/commit/0f3fa3d6f82e4d2aae5c0f918e685e9a5f52c0f1)
