### ISSUE TITLE
Root chainstate hash

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-node#453]
Root hash is defined currently as follows:
```
def calculate_root_hash(chainstate) do
  AccountStateTree.root_hash(chainstate.accounts)
end
```

Root hash should be calculated from all chainstates. Probably we should check how Epoch does that and do the same for compatibility.

**Comment by rdimitrovbg** [comment]
This is done by module [aec tree](https://github.com/aeternity/epoch/blob/master/apps/aecore/src/aec_trees.erl#L291). Since they have more states involved in the preparation of the global chainstate root hash, we can't produce same root hash as theirs.

Of course this could be easily fix once the implementation of other states.

At least the general logic of generating global chainstate root hash could be implemented.

**Comment by rdimitrovbg** [comment]
Blocked until https://github.com/aeternity/elixir-node/pull/481 is merged
