### ISSUE TITLE
Miner is broken on app startup

### ISSUE THREAD

**Issue by grzegorz225** [aeternity/elixir-node#534]
Any function inside Miner is broken if Chain.clear_state() was not called before.
Travis tests are passing because the state of one test interferes with other tests.
How to trigger the bug:
Method 1)
```
mix test test/aecore_miner_test.exs
```
Method 2)
In a new iex session run:
```
Miner.candidate()
```

Demonstration:
```
Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Miner.candidate()
** (UndefinedFunctionError) function nil.header/0 is undefined or private
    nil.header()
    (aecore) lib/aecore/miner/worker.ex:218: Aecore.Miner.Worker.candidate/0
iex(1)> Chain.clear_state()
:ok
iex(2)> Miner.candidate()
%Aecore.Chain.Block{
  header: %Aecore.Chain.Header{
    height: 1,
    miner: <<99, 210, 199, 107, 44, 114, 135, 138, 43, 48, 39, 239, 201, 52,
      238, 172, 44, 135, 64, 118, 56, 31, 255, 129, 135, 65, 209, 160, 156, 83,
      39, 219>>,
    nonce: 0,
    pow_evidence: nil,
    prev_hash: <<21, 156, 171, 146, 198, 198, 172, 36, 173, 41, 235, 64, 240,
      130, 201, 45, 239, 9, 239, 128, 104, 104, 27, 44, 209, 61, 193, 163, 120,
      145, 215, 212>>,
    root_hash: <<7, 3, 205, 135, 51, 13, 113, 21, 34, 145, 226, 126, 34, 201,
      253, 37, 151, 38, 2, 213, 125, 237, 97, 14, 164, 140, 50, 187, 148, 206,
      49, 106>>,
    target: 553713663,
    time: 1534363013120,
    txs_hash: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>,
    version: 14
  },
  txs: []
}
iex(3)>
```

**Comment by cytadela8** [comment]
It seams that issue is triggered by function `Persistance.delete_all_blocks()`. Persistance works properly outside tests, but `aecore_miner_test.exs` calls that function and any subsequent runs error. 

To fully solve this issue and anything similar we should do following:
- Assure tests are properly cleaning the node (create a proper way for clearing node between tests)
- Create test for above mentioned new way of clearning nodes
- Create some test that creates Persistence data and checks consistency of everything after loading.
